# Generated by Django 4.2.10 on 2025-04-26 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_reference',
            field=models.CharField(blank=True, max_length=10, verbose_name='referencia de reserva'),
        ),
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False, verbose_name='completado')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='hora de check-in')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='check_in', to='flights.booking')),
            ],
            options={
                'verbose_name': 'Check-in',
                'verbose_name_plural': 'Check-ins',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='nombre')),
                ('last_name', models.CharField(max_length=100, verbose_name='apellido')),
                ('document_type', models.CharField(choices=[('DNI', 'DNI'), ('PASSPORT', 'Pasaporte'), ('OTHER', 'Otro')], max_length=20, verbose_name='tipo de documento')),
                ('document_number', models.CharField(max_length=30, verbose_name='número de documento')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('nationality', models.CharField(max_length=50, verbose_name='nacionalidad')),
                ('seat_number', models.CharField(blank=True, max_length=10, verbose_name='número de asiento')),
                ('checked_in', models.BooleanField(default=False, verbose_name='check-in realizado')),
                ('boarding_pass_issued', models.BooleanField(default=False, verbose_name='tarjeta de embarque emitida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers_info', to='flights.booking')),
            ],
            options={
                'verbose_name': 'Pasajero',
                'verbose_name_plural': 'Pasajeros',
                'ordering': ['booking', 'last_name', 'first_name'],
                'unique_together': {('booking', 'document_number')},
            },
        ),
    ]
